spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:delivery_db
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: 'classpath:sql/schema.sql'
      data-locations: 'classpath:sql/data.sql'
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true